const insults = [
  // Original 29
  "You're like a cloud. When you disappear, it's a beautiful day!",
  "You bring everyone so much joy when you leave the room!",
  "I'd agree with you, but then we'd both be wrong.",
  "You're not stupid; you just have bad luck thinking.",
  "Your secrets are always safe with me. I never even listen to them.",
  "You're proof that even evolution takes a break sometimes.",
  "You have something on your chin... no, the third one down.",
  "You're like a software update. Whenever I see you, I think, 'Do I really need this right now?'",
  "You bring everyone happiness... you know, when you leave.",
  "You're like a penny—two-faced and not worth much.",
  "You have something on your mind... oh wait, never mind.",
  "You're the reason they put directions on shampoo bottles.",
  "You're like a cloud. Always floating around with no real purpose.",
  "Your jokes are like expired milk—sour and hard to digest.",
  "You're like a candle in the wind... useless when things get tough.",
  "You have something unique—your ability to annoy everyone equally.",
  "You're like a Wi-Fi signal—always weak when needed most.",
  "You're proof that not everyone needs a filter to be unappealing.",
  "Your energy is like a black hole—it just sucks the life out of the room.",
  "You have the perfect face for radio.",
  "You're like a traffic jam—nobody wants you, but here you are.",
  "You're like a broken pencil—pointless.",
  "Your ideas are so original, I'm sure I've heard them all before.",
  "You're living proof that even mistakes can be productive.",
  "You're not lazy; you're just highly motivated to do nothing.",
  "Your brain's running Windows 95—slow and outdated.",
  "You're like a speed bump—nobody likes you, but everyone has to deal with you.",
  "You're like a cloud of mosquitoes—just irritating.",
  "You bring people together... to talk about how annoying you are.",
  
  // New additions
  "You're so full of hot air, I'm surprised you haven't floated away yet.",
  "You're like a Chrome tab—too many open, and nothing working.",
  "You're the human version of a participation trophy.",
  "You couldn't pour water out of a boot with instructions on the heel.",
  "You're not the sharpest tool in the shed—heck, you're not even in the shed.",
  "Your WiFi personality keeps disconnecting.",
  "You have something in common with a brick—both of you just sit there.",
  "You're like a bug in my code—annoying and hard to remove.",
  "You're the reason why shampoo bottles have instructions.",
  "If I had a dollar for every time you said something smart, I'd still be broke.",
  "You're like a screenshot—static and outdated.",
  "Your opinions are like expired coupons—useless.",
  "You're a great example of why some animals eat their young.",
  "You're the kind of person who claps when the plane lands.",
  "You have something special… a special talent for making things awkward.",
  "You're as sharp as a marble.",
  "You're the kind of person that makes people miss the mute button.",
  "You're like Monday morning—nobody likes you.",
  "You're so salty, even the ocean gets jealous.",
  "You bring nothing to the table except crumbs.",
  "You're like a badly written code—unreadable and constantly crashing.",
  "You're the human version of a 404 error.",
  "You're so dry, you make the desert jealous.",
  "You're like a push notification from a game I never downloaded—pointless.",
  "You're what happens when you install a virus instead of an upgrade.",
  "You're like an ad that pops up right when the movie gets good.",
  "You're not even on my to-do list.",
  "You're about as useful as a white crayon.",
  "You're so basic, even HTML wouldn't bother to tag you.",
  "You're the plot twist no one wanted.",
  "You're the echo of a bad idea.",
  "You're the demo version of disappointment.",
  "You're what happens when you try to copy and paste a brain but the file is corrupted."
];