const afrixQuotes = [
  "Hack the world, one line of code at a time. – Jaden-Afrix",
  "Encryption is just a puzzle waiting to be solved. – Jaden-Afrix",
  "I don’t break systems—I rewrite the rules. – Jaden-Afrix",
  "Silence is a hacker’s best disguise. – Jaden-Afrix",
  "We are not the virus, we are the cure. – Jaden-Afrix",
  "Behind every firewall lies a story. – Jaden-Afrix",
  "They control the networks, we control the truth. – Jaden-Afrix",
  "Digital freedom isn’t a myth—it’s a mission. – Jaden-Afrix",
  "My IP address is anonymous. My thoughts are not. – Jaden-Afrix",
  "No badge, no rules—just a keyboard and a mind. – Jaden-Afrix",
  "Coding is my protest. Silence is compliance. – Jaden-Afrix",
  "I don’t hack to destroy. I hack to reveal. – Jaden-Afrix",
  "Your password is weak. Your system is weaker. – Jaden-Afrix",
  "Tor is my street, VPN my vehicle. – Jaden-Afrix",
  "Rebellion is written in code. – Jaden-Afrix",
  "I don’t guess—I dissect. – Jaden-Afrix",
  "In a world of firewalls, be the backdoor. – Jaden-Afrix",
  "I turned syntax into a sword. – Jaden-Afrix",
  "Fake identities. Real intentions. – Jaden-Afrix",
  "Digital footprints don’t lie. – Jaden-Afrix",
  "I exploit bugs, not people. – Jaden-Afrix",
  "Every system has a weakness. I just happen to find them. – Jaden-Afrix",
  "Obscurity is security’s illusion. – Jaden-Afrix",
  "Hackers don’t sleep. We scan. – Jaden-Afrix",
  "My weapon is knowledge, my armor is skill. – Jaden-Afrix",
  "The darknet is my diary. – Jaden-Afrix",
  "I read logs like others read books. – Jaden-Afrix",
  "Don’t trust the cloud, it rains leaks. – Jaden-Afrix",
  "One keystroke can change the world. – Jaden-Afrix",
  "If you fear the hacker, fix your code. – Jaden-Afrix",
  "Hacking isn’t crime, it’s craft. – Jaden-Afrix",
  "Social engineering is art. – Jaden-Afrix",
  "In data we trust, in systems we doubt. – Jaden-Afrix",
  "My keyboard speaks louder than protests. – Jaden-Afrix",
  "Patch or perish. – Jaden-Afrix",
  "I break in to wake you up. – Jaden-Afrix",
  "Hidden ports, open minds. – Jaden-Afrix",
  "Security through obscurity is no security at all. – Jaden-Afrix",
  "Think before you click. I already did. – Jaden-Afrix",
  "Hacktivism isn’t illegal. It’s necessary. – Jaden-Afrix",
  "The system failed you, I just proved it. – Jaden-Afrix",
  "Firewalls fall, but truth stands. – Jaden-Afrix",
  "Data is the new gold. Hackers are the miners. – Jaden-Afrix",
  "I don’t follow breadcrumbs. I erase them. – Jaden-Afrix",
  "Zero days, infinite impact. – Jaden-Afrix",
  "Not all viruses are evil—some expose corruption. – Jaden-Afrix",
  "One root access away from changing everything. – Jaden-Afrix",
  "The first exploit is ignorance. – Jaden-Afrix",
  "The more you hide, the more I seek. – Jaden-Afrix",
  "Digital chains are still chains. – Jaden-Afrix",
  "Never trust a lock you didn’t code. – Jaden-Afrix",
  "Hackers read between the firewalls. – Jaden-Afrix",
  "Binary blood runs through my veins. – Jaden-Afrix",
  "System down, truth up. – Jaden-Afrix",
  "Unmask the code, reveal the lie. – Jaden-Afrix",
  "My internet has no borders. – Jaden-Afrix",
  "Every alert hides a secret. – Jaden-Afrix",
  "Hackers don’t destroy—they expose. – Jaden-Afrix",
  "Your digital shadow is my light. – Jaden-Afrix",
  "Freedom isn’t downloaded. It’s cracked. – Jaden-Afrix",
  "Hackers are the ghosts of the machine. – Jaden-Afrix",
  "My domain is resistance. – Jaden-Afrix",
  "The Matrix was a warning, not fiction. – Jaden-Afrix",
  "No patch for stupidity. – Jaden-Afrix",
  "Truth leaks in packets. – Jaden-Afrix",
  "We rise through root access. – Jaden-Afrix",
  "Hackers were born in shadows. – Jaden-Afrix",
  "The web never forgets. Neither do I. – Jaden-Afrix",
  "Obey nothing. Code everything. – Jaden-Afrix",
  "Hack first, ask later. – Jaden-Afrix",
  "Firewalls burn, ideas don’t. – Jaden-Afrix",
  "Your silence is more dangerous than my intrusion. – Jaden-Afrix",
  "The government has backdoors, we have the keys. – Jaden-Afrix",
  "I code in truth. I compile in chaos. – Jaden-Afrix",
  "Tor whispers what the surface web hides. – Jaden-Afrix",
  "Digital rebellion is not optional. – Jaden-Afrix",
  "You log in. I log everything. – Jaden-Afrix",
  "My payload is awareness. – Jaden-Afrix",
  "I sniff, I spoof, I reveal. – Jaden-Afrix",
  "Don’t fear the hacker. Fear the silence. – Jaden-Afrix",
  "Code is power. Hacking is freedom. – Jaden-Afrix",
  "I didn’t breach you. Your ignorance did. – Jaden-Afrix",
  "If they can monitor you, I can unmask them. – Jaden-Afrix",
  "I see truth in logs and lies in headlines. – Jaden-Afrix",
  "I enter quietly, but I exit loudly. – Jaden-Afrix",
  "Hackers are not criminals. We are consequences. – Jaden-Afrix",
  "There’s no 404 in justice. – Jaden-Afrix",
  "Where they encrypt lies, I decrypt truth. – Jaden-Afrix",
  "Cyberwarriors don’t bleed—they compile. – Jaden-Afrix",
  "They fear what they can’t trace. – Jaden-Afrix",
  "The web is our battlefield. The code is our weapon. – Jaden-Afrix",
  "We wear hoodies, not masks. – Jaden-Afrix",
  "If you can’t protect it, don’t store it. – Jaden-Afrix",
  "I exploit the gaps you forgot to close. – Jaden-Afrix",
  "Hackers are today’s philosophers. – Jaden-Afrix",
  "The only firewall you can’t bypass is truth. – Jaden-Afrix",
  "Logs don’t lie—admins do. – Jaden-Afrix",
  "We are Anonymous, but I am Jaden-Afrix. – Jaden-Afrix"
];